### ISSUE TITLE
SubCommands return an Execution Error with a greedy argument

### ISSUE THREAD

**Issue by Foxikle** [Mqzn/mCommands#8]
### Creating a greedy argument using a regular command
```java
@Command(name = "test")
public class Testcmd {
    @Default
    @ExecutionMeta(syntax = "<str>")
    public void defaultExecution(@NotNull CommandSender sender, @Arg(id = "str") @Greedy String str) {
        sender.sendMessage("test -> " + str);
    }
}
```
works as intended.
(using `/test hello im a greedy string`)

### Creating a greedy argument in a sub command
Parent class
```java
@Command(name = "parent")
@SubCommand(ChildCmd.class)
public class ParentCmd {
    @Default
    public void defaultExecution(@NotNull CommandSender sender) {
        sender.sendMessage("hi this is the parent");
    }
}
```
Sub command class
```java
@ExecutionMeta(syntax = "<str>")
@SubCommandInfo(name = "greedy")
public class ChildCmd {
    @SubCommandExecution
    public void execute(@NotNull CommandSender sender, @Arg(id = "str") @Greedy String str) {
        sender.sendMessage("child -> " + str);
    }
}
```
The sub command produces an error when executing `/parent greedy hello im a greedy string`

![image](https://github.com/Mqzn/mCommands/assets/89223211/8ceec310-5ef9-475e-951a-7a10935d1bae)

**Potentially Useful Info**
- Version: 1.1.2
- Spigot Module
- MC 1.20.1

Cheers!
~ Foxikle

**Comment by Mqzn** [comment]
Thank you for your clear explanation. I will be working on a fix for this bug !
